### ISSUE TITLE
Compatibility with laravel. Add autoload.php file

### ISSUE THREAD

**Issue by kousiksatish** [ckeditor/ckeditor4-releases#42]
https://packagist.org/packages/ckeditor/ckeditor
I used this for installing ckeditor to my laravel project
When I install the package through composer, it copies the files or all assets(js, css) to the vendor folder (which contains all the dependencies).
But thats not enough, we cannot use the assets from the vendor folder directly. We need to copy it to the public folder.
So, I recommend you to provide a autoload.php file that will automatically copy these files to the public folder, from where we can use it to create views.
Without this, the package is useless and we have no other choice other than manually copying the files to the public folder.

**Comment by Yahav** [comment]
Just use Mix to copy the assets where ever you'd like.

**Comment by f1ames** [comment]
Closing since there were no more issues/comments related to this topic for a long time.
