### ISSUE TITLE
Provide working example for "Try it out" link on our npm package page.

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4-releases#50]
There is "Try it out Test ckeditor in your browser." link/box in ckeditor package page which uses tonicdev.com playground/sandbox to show packages examples in browser.
For CKEditor it does not work out of the box so we should provide working example. 

I posted an issue on npm/newww, asking how it should be done correctly for frontend packages like CKEditor, see https://github.com/npm/newww/issues/1891.

**Comment by boucher** [comment]
I've opened a pull request here: https://github.com/ckeditor/ckeditor-releases/pull/51

**Comment by mlewand** [comment]
@boucher thanks a lot! We'll check it soon! :)

**Comment by f1ames** [comment]
Closing as not really relevant anymore. Also from what I see Tonic evolved into RunKit so the related PR may no longer work after such a long time.
