### ISSUE TITLE
Separate distribution channels for basic / full / standard preset

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4-releases#69]
As a result of discussion in https://github.com/ckeditor/ckeditor-releases/issues/41 we got a better way of handling releases.

The idea is to keep separate endpoints for each preset:

* keep ckeditor/ckeditor pointing at `standard-all` preset
* ckeditor/ckeditor-basic
* ckeditor/ckeditor-standard
* ckeditor/ckeditor-full

Also we'd have to create a separate repo for each preset, and update our release script to do this automatically.

**Comment by f1ames** [comment]
Closing as not really relevant anymore as it seems we are happy we the things the way there are here.
